#!/bin/bash
# Project initialization script
# Generated by dev-protocol

set -e

echo "Starting Elyse Speech Visualizer development environment..."

# Install dependencies
if [ -f "package.json" ]; then
  echo "Installing npm dependencies..."
  npm install
fi

# Load environment variables
if [ -f ".env.local" ]; then
  echo "Loading environment variables..."
  export $(cat .env.local | grep -v '^#' | xargs)
else
  echo "Warning: .env.local not found. Create it with your API keys."
fi

# Start dev server
if [ -f "package.json" ]; then
  echo "Starting dev server..."
  npm run dev &
  DEV_PID=$!
  echo "Dev server PID: $DEV_PID"
  sleep 3
fi

echo "Environment ready"
echo "Dev server running at http://localhost:5173"
