#!/bin/bash
# Project initialization script
# Generated by dev-protocol

set -e

echo "🎨 Starting Elyse Speech Visualizer development environment..."

# Check if package.json exists (project scaffolded)
if [ ! -f "package.json" ]; then
  echo "⚠️  No package.json found - project needs scaffolding"
  echo ""
  echo "Run the first sprint to scaffold the project:"
  echo "  /dev-protocol:sprint"
  exit 0
fi

# Install dependencies
echo "📦 Installing dependencies..."
npm install

# Start dev server
echo "🚀 Starting dev server..."
npm run dev &
DEV_PID=$!
echo "Dev server PID: $DEV_PID"

# Wait for server to be ready
echo "⏳ Waiting for server to start..."
sleep 3

echo ""
echo "✅ Environment ready!"
echo "   Dev server running at http://localhost:5173 (or similar)"
echo ""
echo "To stop: kill $DEV_PID"
